### ISSUE TITLE
research: use AVX2 for cksum.c

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/slirp4netns#15]
https://github.com/snabbco/snabb/blob/master/src/arch/avx2.c

**Comment by AkihiroSuda** [comment]
Or maybe "New" algorithm described in https://blogs.igalia.com/dpino/2018/06/14/fast-checksum-computation/

**Comment by AkihiroSuda** [comment]
`CFLAGS=-O3 -msse4.2 -mavx2` enables xmm/ymm registers automatically (confirmed with objdump), but not so significantly effective

**Comment by giuseppe** [comment]
@sthibaul we are currently using the slirp implementation in qemu for slirp4netns so that we can configure a network namespace for an unprivileged network.

IMHO, I think such optimizations, when possible, should be added to qemu so that both projects take advantage of them.

@sthibaul Would it be possible to make the implementation in qemu easier to use from other packages?  Willing to accept patches?

**Comment by sthibaul** [comment]
@giuseppe Actually there is already a libslirp based on qemu's slirp, https://github.com/rd235/libslirp . This was discussed on qemu-devel last year: http://lists.nongnu.org/archive/html/qemu-devel/2017-02/msg01092.html but it didn't really converge.

I'd say further discussions should happen on qemu-devel, at least :)

The thing that happened is that within qemu, slirp/ was made to use more and more qemu-provided helpers, which thus got further from making it a libslirp. I guess we might have to really get it outside qemu and make it a qemu dependency, to actually make it shareable and maintainable.

**Comment by giuseppe** [comment]
libslirp adds more complexity and it looks like it is not really maintained, last commit was more than a year ago.  Copying the code as libslirp and slirp4netns are doing is fine, but what I am worring about is diverging and missing future changes.  I think a "copylib" is fine, and making the qemu code guarded by preprocessor macros should be enough, but yes maybe qemu-devel is a better place for this discussion :-)

**Comment by sthibaul** [comment]
Giuseppe Scrivano, le ven. 10 août 2018 02:32:42 -0700, a ecrit:
> libslirp adds more complexity

Which complexity?

> and it looks like it is not really maintained,

Well, that's not a reason for not continuing on its grounds :)
Better gather efforts that letting it continue to be dispersed.

> last commit was more than a year ago. Copying the code as libslirp and
> slirp4netns are doing is fine, but what I am worring about is diverging and
> missing future changes. I think a "copylib" is fine, and making the qemu code
> guarded by preprocessor macros should be enough, but yes maybe qemu-devel is a
> better place for this discussion :-)

Yes, because that's precisely what happened: qemu developers
will definitely continue tending to make that slirp/ piece look
more qemu-ish, and using it as such in other projects will keep
being a maintenance burden.  While making it a separate project
would make things clear.  The difficult thing is setting up an
interface.  Configuration and incoming/outgoing packets is not complex.
Saving/restoring the state is.

**Comment by giuseppe** [comment]
> Which complexity?

it adds a socketpair for getting events from slirp.  @AkihiroSuda measured this has an impact on the performance.

**Comment by AkihiroSuda** [comment]
Closing, as perhaps we should rather look into #16
